export type RecordKind = "system" | "board" | "suspension" | "support" | "rule" | "quantity";
export type ReferenceRecord = { id:string; kind:RecordKind; title:string; summary:string; sourcePage:number; status:"Publié"|"À valider"; data:Record<string,string|number|boolean|null|string[]> };

const boardNames = ["Placoplatre BA 6","Placoplatre BA 13","Placoplatre BA 15","Placoplatre BA 18","Placo Phonique","Placoflam","Lisaplac","4PRO","PlacoPremium","Placo Activ’Air","Lisaflam","Placo Multiconforts","Placo Infinaé"];

export const f530Records:ReferenceRecord[] = [
 {id:"F530-SYSTEM",kind:"system",title:"Plafond Placostil® sur fourrures Stil® F 530",summary:"Plaques Placo vissées sur ossature métallique suspendue, pour supports bois, métal, béton ou hourdis.",sourcePage:104,status:"Publié",data:{domaines:["Logement","ERP","IGH","Bureaux","Locaux industriels et commerciaux"],formes:["Horizontal","Incliné","Cintré","Redents"],edition:"Juin 2025",reference:"DTU 25.41"}},
 ...boardNames.map((title,index):ReferenceRecord=>({id:`BOARD-${String(index+1).padStart(2,"0")}`,kind:"board",title,summary:"Plaque associée au système F 530.",sourcePage:104,status:"Publié",data:{compatible:true}})),
 {id:"SUSP-CLM",kind:"suspension",title:"Suspente courte, longue ou maxi Stil F 530",summary:"Réglage de 20 à 280 mm.",sourcePage:105,status:"Publié",data:{reglage_min_mm:20,reglage_max_mm:280,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",support:"Bois"}},
 {id:"SUSP-SEC600",kind:"suspension",title:"Suspente sécable 600 Stil F 530",summary:"Réglage de 80 à 580 mm.",sourcePage:105,status:"Publié",data:{reglage_min_mm:80,reglage_max_mm:580,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",support:"Bois"}},
 {id:"SUSP-CLIPLAINE",kind:"suspension",title:"Suspente Cliplaine Stil F 530",summary:"Deux réglages possibles : 280 ou 370 mm.",sourcePage:105,status:"Publié",data:{reglages_mm:["280","370"],entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",support:"Bois"}},
 {id:"SUSP-CAVALIER",kind:"suspension",title:"Cavalier Stil F 530",summary:"Avec suspente articulée Stil SA et tige filetée Ø 6 mm.",sourcePage:105,status:"Publié",data:{reglage:"> 20 mm",entraxe_suspentes_m:1.2,charge_rupture_kg:600,fixation:"Cheville métallique pour tige Ø 6 mm",support:"Bois"}},
 {id:"SUSP-INTEGRA2",kind:"suspension",title:"Suspente Integra 2",summary:"Suspente pour solivage bois, réglable de 0 à 300 mm.",sourcePage:105,status:"Publié",data:{reglage_min_mm:0,reglage_max_mm:300,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",support:"Bois",origine:"Référence ajoutée par l’administrateur"}},
 {id:"SUP-BOIS-SOLIVAGE",kind:"support",title:"Solivage d’un plancher bois",summary:"Fixation sous solives bois avec suspente Stil® F 530 adaptée à la hauteur du plénum.",sourcePage:105,status:"Publié",data:{entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",solutions_suspension:["Suspente courte, longue ou maxi Stil F 530 · réglage 20 à 280 mm","Suspente sécable 600 Stil F 530 · réglage 80 à 580 mm","Suspente Cliplaine Stil F 530 · réglage 280 ou 370 mm","Cavalier Stil F 530 + suspente articulée Stil SA + tige filetée Ø 6 mm · réglage > 20 mm"],note:"En régions ventées sous rampants, les têtes de suspentes peuvent recevoir des butées résilientes en néoprène."}},
 {id:"SUP-BETON",kind:"support",title:"Dalle béton",summary:"Cheville Ø 6 + tendeur + cavalier Stil F 530, ou cavalier dB-F.",sourcePage:106,status:"Publié",data:{reglage:"> 20 mm",charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"SUP-HOURDIS-H",kind:"support",title:"Hourdis béton · H Stil F 530",summary:"Insertion forcée entre poutrelle et hourdis.",sourcePage:106,status:"Publié",data:{reglage:"20 à 40 mm",charge_suspente_kg:63,poids_plafond_kg_m2:88,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"SUP-HOURDIS-HL",kind:"support",title:"Hourdis béton · HL Stil F 530",summary:"Insertion forcée entre poutrelle et hourdis.",sourcePage:106,status:"Publié",data:{reglage:"20 à 40 mm",charge_suspente_kg:63,poids_plafond_kg_m2:88,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"SUP-HOURDIS-HL-SUSP",kind:"support",title:"Hourdis · HL + suspente C/L/M",summary:"Solution pour plénum de 60 à 330 mm.",sourcePage:106,status:"Publié",data:{reglage:"60 à 330 mm",charge_suspente_kg:40,poids_plafond_kg_m2:55,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"SUP-HOURDIS-HL-ROD",kind:"support",title:"Hourdis · HL + tige Ø 6 + cavalier",summary:"Solution pour plénum de 60 à 1 000 mm.",sourcePage:106,status:"Publié",data:{reglage:"60 à 1 000 mm",charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"SUP-SM8",kind:"support",title:"Plancher mixte ou charpente métallique",summary:"Attache Stil SM8 + cavalier, sur aile de poutrelle inférieure à 8 mm.",sourcePage:106,status:"Publié",data:{reglage:"> 20 mm",charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2,isolant:"< 6 kg/m²"}},
 {id:"RULE-ISO-LT6",kind:"rule",title:"Isolant inférieur à 6 kg/m²",summary:"Entraxe maximal des fourrures : 60 cm.",sourcePage:105,status:"Publié",data:{poids_min_kg_m2:0,poids_max_exclu_kg_m2:6,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-6-10",kind:"rule",title:"Isolant de 6 kg/m² à moins de 10 kg/m²",summary:"Entraxe maximal des fourrures : 50 cm.",sourcePage:105,status:"Publié",data:{poids_min_inclus_kg_m2:6,poids_max_exclu_kg_m2:10,entraxe_fourrures_m:0.5,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-10-15",kind:"rule",title:"Isolant de 10 à 15 kg/m²",summary:"Entraxe maximal des fourrures : 40 cm.",sourcePage:105,status:"Publié",data:{poids_min_inclus_kg_m2:10,poids_max_inclus_kg_m2:15,entraxe_fourrures_m:0.4,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-GT15",kind:"rule",title:"Isolant supérieur à 15 kg/m²",summary:"Configuration bloquée : aucune règle n’est fournie dans les pages étudiées.",sourcePage:105,status:"À valider",data:{poids_min_exclu_kg_m2:15,action:"Bloquer la configuration"}},
 {id:"RULE-POSE",kind:"rule",title:"Pose des plaques",summary:"Plaques perpendiculaires ; entraxe réduit à 40 cm si pose parallèle ou plaque hydrofugée.",sourcePage:108,status:"Publié",data:{entraxe_reduit_m:0.4,vis_standard_cm:30,vis_feu_cm:15}},
 {id:"RULE-RIVE",kind:"rule",title:"Rail périphérique",summary:"Cornière Stil CR2 ou rail Stil F 530 fixé tous les 60 cm maximum.",sourcePage:107,status:"Publié",data:{entraxe_fixations_max_cm:60}},
 {id:"RULE-JOINTS",kind:"rule",title:"Joints de fractionnement",summary:"Aux joints du bâtiment, changements de support ou d’orientation, puis tous les 300 m² ou 25 m linéaires.",sourcePage:109,status:"Publié",data:{surface_max_m2:300,longueur_max_m:25}},
 {id:"RULE-LOAD",kind:"rule",title:"Charge ponctuelle d’accessoire",summary:"2 daN par surface de 1,20 × 1,20 m.",sourcePage:109,status:"Publié",data:{charge_dan:2,surface_reference:"1,20 × 1,20 m"}},
 ...([0.4,0.5,0.6] as const).flatMap(spacing=>[1,2].map((layers):ReferenceRecord=>{const i=spacing===0.4?0:spacing===0.5?1:2;return {id:`QTY-${Math.round(spacing*100)}-${layers}L`,kind:"quantity",title:`Quantitatif ${layers===1?"simple":"double"} peau · entraxe ${Math.round(spacing*100)} cm`,summary:"Quantités indicatives pour 1 m², plafond de référence 8 × 10 m.",sourcePage:109,status:"Publié",data:{entraxe_fourrures_m:spacing,peaux:layers,plaque_m2:layers===1?1.05:2.10,fourrure_f530_ml:[2.52,2.10,1.79][i],rail_f530_ml:0.47,suspente_unite:[2.20,1.84,1.56][i],eclisse_unite:spacing===0.4?null:spacing===0.5?0.25:0.21,vis_premiere_peau_unite:layers===1?[20,17,15][i]:[13,11,10][i],vis_deuxieme_peau_unite:layers===2?[20,17,15][i]:null,bande_joint_ml:1.58,enduit_poudre_kg:0.37,enduit_pret_emploi_kg:0.53,entretoise_stil_flam_unite:spacing===0.6?1.68:null,base:"1 m² · plafond 8 × 10 m",note_enduit:"Poudre OU prêt à l’emploi",note_vis:"Longueur > épaisseur totale des plaques + 10 mm"}}}))
];

export const recordLabels:Record<RecordKind,string>={system:"Système",board:"Plaques",suspension:"Suspentes",support:"Supports",rule:"Règles",quantity:"Quantitatifs"};
