export type RecordKind = "work" | "system" | "product_family" | "brand" | "product" | "product_model" | "commercial_reference" | "product_reference" | "board" | "suspension" | "support" | "rule" | "quantity" | "source";
export type ReferenceRecord = { id:string; kind:RecordKind; title:string; summary:string; sourcePage:number; status:"Publié"|"À valider"; data:Record<string,string|number|boolean|null|string[]> };

const boardNames = ["Placoplatre BA 6","Placoplatre BA 13","Placoplatre BA 15","Placoplatre BA 18","Placo Phonique","Placoflam","Lisaplac","4PRO","PlacoPremium","Placo Activ’Air","Lisaflam","Placo Multiconforts","Placo Infinaé"];
const suspensionProducts = [
 ["SUSP-CLM","Suspente courte, longue ou maxi Stil F 530"],["SUSP-SEC600","Suspente sécable 600 Stil F 530"],["SUSP-CLIPLAINE","Suspente Cliplaine Stil F 530"],["SUSP-CAVALIER","Cavalier Stil F 530"],["SUSP-INTEGRA2","Suspente Integra 2"],["SUSP-BETON-CAV","Cheville Ø 6 + tendeur + cavalier Stil F 530"],["SUP-HOURDIS-H","Suspente H Stil F 530"],["SUP-HOURDIS-HL","Suspente HL Stil F 530"],["SUP-HOURDIS-HL-SUSP","Suspente HL + suspente C/L/M Stil F 530"],["SUP-HOURDIS-HL-ROD","Suspente HL + tige Ø 6 + cavalier"],["SUP-SM8","Attache Stil SM8 + cavalier Stil F 530"]
];

export const productTechnicalDefaults:Record<string,ReferenceRecord["data"]> = {
 "PRODUCT-SUSP-STIL-F530":{technical_record_id:"SUSP-CLM",support_id:"SUP-BOIS-SOLIVAGE",reglage_mode:"continu",reglage_min_mm:20,reglage_max_mm:280,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"},
 "CATALOG-PRODUCT-SUSP-INTEGRA2":{technical_record_id:"SUSP-INTEGRA2",support_id:"SUP-BOIS-SOLIVAGE",reglage_mode:"continu",reglage_min_mm:0,reglage_max_mm:300,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"},
 "CATALOG-PRODUCT-SUSP-SEC600":{technical_record_id:"SUSP-SEC600",support_id:"SUP-BOIS-SOLIVAGE",reglage_mode:"continu",reglage_min_mm:80,reglage_max_mm:580,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"},
 "CATALOG-PRODUCT-SUSP-CLIPLAINE":{technical_record_id:"SUSP-CLIPLAINE",support_id:"SUP-BOIS-SOLIVAGE",reglage_mode:"valeurs_discretes",reglage_min_mm:280,reglage_max_mm:370,reglages_mm:["280","370"],entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"}
};

export const f530Records:ReferenceRecord[] = [
 {id:"WORK-CEILINGS",kind:"work",title:"Plafonds",summary:"Ouvrages horizontaux, inclinés ou cintrés situés en partie haute d’un local.",sourcePage:104,status:"Publié",data:{slug:"plafonds"}},
 {id:"F530-SYSTEM",kind:"system",title:"Plafond Placostil® sur fourrures Stil® F 530",summary:"Plaques Placo vissées sur ossature métallique suspendue, pour supports bois, métal, béton ou hourdis.",sourcePage:104,status:"Publié",data:{domaines:["Logement","ERP","IGH","Bureaux","Locaux industriels et commerciaux"],formes:["Horizontal","Incliné","Cintré","Redents"],edition:"Juin 2025",reference:"DTU 25.41"}},
 {id:"FAMILY-BOARDS",kind:"product_family",title:"Plaques de plâtre",summary:"Parements en plaques de plâtre.",sourcePage:104,status:"Publié",data:{code:"plaques",unite_technique:"m²"}},
 {id:"FAMILY-SUSPENSIONS",kind:"product_family",title:"Suspentes",summary:"Éléments de liaison entre le support et les fourrures.",sourcePage:105,status:"Publié",data:{code:"suspentes",unite_technique:"unité"}},
 {id:"FAMILY-FURRINGS",kind:"product_family",title:"Fourrures",summary:"Profilés métalliques constituant l’ossature du plafond.",sourcePage:104,status:"Publié",data:{code:"fourrures",unite_technique:"mètre linéaire"}},
 {id:"FAMILY-RAILS",kind:"product_family",title:"Rails et cornières",summary:"Profilés périphériques du plafond.",sourcePage:107,status:"Publié",data:{code:"rails",unite_technique:"mètre linéaire"}},
 {id:"FAMILY-SCREWS",kind:"product_family",title:"Vis",summary:"Fixations des plaques et des suspentes.",sourcePage:108,status:"Publié",data:{code:"vis",unite_technique:"unité"}},
 {id:"FAMILY-TAPES",kind:"product_family",title:"Bandes à joint",summary:"Bandes pour le traitement des joints.",sourcePage:109,status:"Publié",data:{code:"bandes",unite_technique:"mètre linéaire"}},
 {id:"FAMILY-COMPOUNDS",kind:"product_family",title:"Enduits",summary:"Enduits en poudre ou prêts à l’emploi.",sourcePage:109,status:"Publié",data:{code:"enduits",unite_technique:"kg"}},
 {id:"FAMILY-INSULATION",kind:"product_family",title:"Isolants",summary:"Isolants en laine minérale posés sur l’ossature.",sourcePage:104,status:"Publié",data:{code:"isolants",unite_technique:"m²"}},
 {id:"BRAND-PLACO",kind:"brand",title:"Placo®",summary:"Marque des produits du système Placostil® F 530.",sourcePage:104,status:"Publié",data:{code:"placo"}},
 {id:"PRODUCT-SUSP-STIL-F530",kind:"product",title:"Suspente Stil® F 530",summary:"Famille de suspentes pour fourrures Stil® F 530 sur solivage bois.",sourcePage:105,status:"Publié",data:{family_id:"FAMILY-SUSPENSIONS",brand_id:"BRAND-PLACO",...productTechnicalDefaults["PRODUCT-SUSP-STIL-F530"]}},
 {id:"MODEL-SUSP-STIL-F530-COURTE",kind:"product_model",title:"Courte",summary:"Modèle court de la suspente Stil® F 530.",sourcePage:105,status:"À valider",data:{product_id:"PRODUCT-SUSP-STIL-F530",dimension_mm:null,reglage_min_mm:null,reglage_max_mm:null,technical_record_id:"SUSP-CLM"}},
 {id:"MODEL-SUSP-STIL-F530-LONGUE",kind:"product_model",title:"Longue",summary:"Modèle long de la suspente Stil® F 530.",sourcePage:105,status:"À valider",data:{product_id:"PRODUCT-SUSP-STIL-F530",dimension_mm:null,reglage_min_mm:null,reglage_max_mm:null,technical_record_id:"SUSP-CLM"}},
 {id:"MODEL-SUSP-STIL-F530-MAXI",kind:"product_model",title:"Maxi",summary:"Modèle maxi de la suspente Stil® F 530.",sourcePage:105,status:"À valider",data:{product_id:"PRODUCT-SUSP-STIL-F530",dimension_mm:null,reglage_min_mm:null,reglage_max_mm:null,technical_record_id:"SUSP-CLM"}},
 {id:"CATALOG-PRODUCT-SUSP-INTEGRA2",kind:"product",title:"Suspente Integra 2",summary:"Suspente réglable pour solivage bois.",sourcePage:105,status:"Publié",data:{family_id:"FAMILY-SUSPENSIONS",brand_id:"BRAND-PLACO",...productTechnicalDefaults["CATALOG-PRODUCT-SUSP-INTEGRA2"]}},
 {id:"MODEL-SUSP-INTEGRA2-300",kind:"product_model",title:"0–300 mm",summary:"Modèle réglable de 0 à 300 mm.",sourcePage:105,status:"Publié",data:{product_id:"CATALOG-PRODUCT-SUSP-INTEGRA2",dimension_mm:300,reglage_min_mm:0,reglage_max_mm:300,technical_record_id:"SUSP-INTEGRA2"}},
 {id:"CATALOG-PRODUCT-SUSP-SEC600",kind:"product",title:"Suspente sécable Stil® F 530",summary:"Suspente sécable pour solivage bois.",sourcePage:105,status:"Publié",data:{family_id:"FAMILY-SUSPENSIONS",brand_id:"BRAND-PLACO",...productTechnicalDefaults["CATALOG-PRODUCT-SUSP-SEC600"]}},
 {id:"MODEL-SUSP-SEC600",kind:"product_model",title:"600 mm",summary:"Modèle réglable de 80 à 580 mm.",sourcePage:105,status:"Publié",data:{product_id:"CATALOG-PRODUCT-SUSP-SEC600",dimension_mm:600,reglage_min_mm:80,reglage_max_mm:580,technical_record_id:"SUSP-SEC600"}},
 {id:"CATALOG-PRODUCT-SUSP-CLIPLAINE",kind:"product",title:"Suspente Cliplaine® Stil® F 530",summary:"Suspente pour solivage bois et isolation.",sourcePage:105,status:"Publié",data:{family_id:"FAMILY-SUSPENSIONS",brand_id:"BRAND-PLACO",...productTechnicalDefaults["CATALOG-PRODUCT-SUSP-CLIPLAINE"]}},
 {id:"MODEL-SUSP-CLIPLAINE-280",kind:"product_model",title:"280 mm",summary:"Modèle de 280 mm.",sourcePage:105,status:"Publié",data:{product_id:"CATALOG-PRODUCT-SUSP-CLIPLAINE",dimension_mm:280,reglage_min_mm:280,reglage_max_mm:280,technical_record_id:"SUSP-CLIPLAINE"}},
 {id:"MODEL-SUSP-CLIPLAINE-370",kind:"product_model",title:"370 mm",summary:"Modèle de 370 mm.",sourcePage:105,status:"Publié",data:{product_id:"CATALOG-PRODUCT-SUSP-CLIPLAINE",dimension_mm:370,reglage_min_mm:370,reglage_max_mm:370,technical_record_id:"SUSP-CLIPLAINE"}},
 {id:"PRODUCT-F530",kind:"product_reference",title:"Fourrure Stil® F 530",summary:"Fourrure métallique du système F 530.",sourcePage:104,status:"Publié",data:{family_id:"FAMILY-FURRINGS",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"pièce",longueur_mm:null}},
 {id:"PRODUCT-RAIL-F530",kind:"product_reference",title:"Rail Stil® F 530",summary:"Rail périphérique du système F 530.",sourcePage:104,status:"Publié",data:{family_id:"FAMILY-RAILS",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"pièce",longueur_mm:null}},
 {id:"PRODUCT-TTPC35",kind:"product_reference",title:"Vis TTPC 35",summary:"Vis de fixation des plaques ou suspentes.",sourcePage:105,status:"Publié",data:{family_id:"FAMILY-SCREWS",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"boîte",longueur_mm:35}},
 {id:"PRODUCT-BAND",kind:"product_reference",title:"Bande à joint Placoplatre®",summary:"Bande à joint grand rouleau.",sourcePage:109,status:"Publié",data:{family_id:"FAMILY-TAPES",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"rouleau"}},
 {id:"PRODUCT-COMPOUND-POWDER",kind:"product_reference",title:"Enduit Placojoint®",summary:"Enduit à joint en poudre.",sourcePage:109,status:"Publié",data:{family_id:"FAMILY-COMPOUNDS",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"sac"}},
 {id:"PRODUCT-COMPOUND-READY",kind:"product_reference",title:"Enduit Placomix®",summary:"Enduit à joint prêt à l’emploi.",sourcePage:109,status:"Publié",data:{family_id:"FAMILY-COMPOUNDS",brand_id:"BRAND-PLACO",reference_fabricant:null,conditionnement:null,prix_ht:null,unite_vente:"seau"}},
 ...boardNames.map((title,index):ReferenceRecord=>({id:`BOARD-${String(index+1).padStart(2,"0")}`,kind:"board",title,summary:"Plaque associée au système F 530.",sourcePage:104,status:"Publié",data:{compatible:true}})),
 ...boardNames.map((title,index):ReferenceRecord=>({id:`PRODUCT-BOARD-${String(index+1).padStart(2,"0")}`,kind:"product_reference",title,summary:"Référence de plaque compatible avec le système F 530.",sourcePage:104,status:"Publié",data:{family_id:"FAMILY-BOARDS",brand_id:"BRAND-PLACO",technical_record_id:`BOARD-${String(index+1).padStart(2,"0")}`,reference_fabricant:null,dimensions:null,conditionnement:null,prix_ht:null,unite_vente:"plaque"}})),
 ...suspensionProducts.map(([technicalId,title]):ReferenceRecord=>({id:`PRODUCT-${technicalId}`,kind:"product_reference",title,summary:"Référence de suspension ou de fixation compatible F 530.",sourcePage:technicalId.startsWith("SUSP-")&&technicalId!=="SUSP-BETON-CAV"?105:106,status:"Publié",data:{family_id:"FAMILY-SUSPENSIONS",brand_id:"BRAND-PLACO",technical_record_id:technicalId,reference_fabricant:null,dimensions:null,conditionnement:null,prix_ht:null,unite_vente:"pièce"}})),
 {id:"SUSP-CLM",kind:"suspension",title:"Suspente courte, longue ou maxi Stil F 530",summary:"Réglage de 20 à 280 mm.",sourcePage:105,status:"Publié",data:{support_id:"SUP-BOIS-SOLIVAGE",reglage_min_mm:20,reglage_max_mm:280,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"}},
 {id:"SUSP-SEC600",kind:"suspension",title:"Suspente sécable 600 Stil F 530",summary:"Réglage de 80 à 580 mm.",sourcePage:105,status:"Publié",data:{support_id:"SUP-BOIS-SOLIVAGE",reglage_min_mm:80,reglage_max_mm:580,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"}},
 {id:"SUSP-CLIPLAINE",kind:"suspension",title:"Suspente Cliplaine Stil F 530",summary:"Deux réglages possibles : 280 ou 370 mm.",sourcePage:105,status:"Publié",data:{support_id:"SUP-BOIS-SOLIVAGE",reglages_mm:["280","370"],entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente"}},
 {id:"SUSP-CAVALIER",kind:"suspension",title:"Cavalier Stil F 530",summary:"Avec suspente articulée Stil SA et tige filetée Ø 6 mm.",sourcePage:105,status:"Publié",data:{support_id:"SUP-BOIS-SOLIVAGE",reglage_min_exclu_mm:20,entraxe_suspentes_m:1.2,charge_rupture_kg:600,fixation:"Cheville métallique pour tige Ø 6 mm"}},
 {id:"SUSP-INTEGRA2",kind:"suspension",title:"Suspente Integra 2",summary:"Suspente pour solivage bois, réglable de 0 à 300 mm.",sourcePage:105,status:"Publié",data:{support_id:"SUP-BOIS-SOLIVAGE",reglage_min_mm:0,reglage_max_mm:300,entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",origine:"Référence ajoutée par l’administrateur"}},
 {id:"SUP-BOIS-SOLIVAGE",kind:"support",title:"Solivage d’un plancher bois",summary:"Fixation sous solives bois avec suspente Stil® F 530 adaptée à la hauteur du plénum.",sourcePage:105,status:"Publié",data:{entraxe_suspentes_m:1.2,fixation:"2 vis TTPC 35 par suspente",solutions_suspension:["Suspente courte, longue ou maxi Stil F 530 · réglage 20 à 280 mm","Suspente sécable 600 Stil F 530 · réglage 80 à 580 mm","Suspente Cliplaine Stil F 530 · réglage 280 ou 370 mm","Cavalier Stil F 530 + suspente articulée Stil SA + tige filetée Ø 6 mm · réglage > 20 mm"],note:"En régions ventées sous rampants, les têtes de suspentes peuvent recevoir des butées résilientes en néoprène."}},
 {id:"SUP-BETON",kind:"support",title:"Dalle béton",summary:"Support en dalle béton.",sourcePage:106,status:"Publié",data:{}},
 {id:"SUP-HOURDIS",kind:"support",title:"Plancher hourdis béton",summary:"Plancher avec poutrelles et hourdis béton.",sourcePage:106,status:"Publié",data:{}},
 {id:"SUP-METAL",kind:"support",title:"Charpente métallique",summary:"Fixation sur aile de poutrelle métallique inférieure à 8 mm.",sourcePage:106,status:"Publié",data:{}},
 {id:"SUSP-BETON-CAV",kind:"suspension",title:"Cheville Ø 6 + tendeur + cavalier Stil F 530",summary:"Montage sous dalle béton, avec cavalier Stil F 530 ou cavalier dB-F.",sourcePage:106,status:"Publié",data:{support_id:"SUP-BETON",reglage_min_exclu_mm:20,entraxe_suspentes_m:1.2,charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90,fixation:"Cheville métallique pour tige filetée"}},
 {id:"SUP-HOURDIS-H",kind:"suspension",title:"Suspente H Stil F 530",summary:"Insertion forcée entre poutrelle et hourdis.",sourcePage:106,status:"Publié",data:{support_id:"SUP-HOURDIS",reglage_min_mm:20,reglage_max_mm:40,entraxe_suspentes_m:1.2,charge_suspente_kg:63,poids_plafond_kg_m2:88}},
 {id:"SUP-HOURDIS-HL",kind:"suspension",title:"Suspente HL Stil F 530",summary:"Insertion forcée entre poutrelle et hourdis.",sourcePage:106,status:"Publié",data:{support_id:"SUP-HOURDIS",reglage_min_mm:20,reglage_max_mm:40,entraxe_suspentes_m:1.2,charge_suspente_kg:63,poids_plafond_kg_m2:88}},
 {id:"SUP-HOURDIS-HL-SUSP",kind:"suspension",title:"Suspente HL + suspente C/L/M Stil F 530",summary:"Solution pour plénum de 60 à 330 mm.",sourcePage:106,status:"Publié",data:{support_id:"SUP-HOURDIS",reglage_min_mm:60,reglage_max_mm:330,entraxe_suspentes_m:1.2,charge_suspente_kg:40,poids_plafond_kg_m2:55}},
 {id:"SUP-HOURDIS-HL-ROD",kind:"suspension",title:"Suspente HL + tige Ø 6 + cavalier",summary:"Solution pour plénum de 60 à 1 000 mm.",sourcePage:106,status:"Publié",data:{support_id:"SUP-HOURDIS",reglage_min_mm:60,reglage_max_mm:1000,entraxe_suspentes_m:1.2,charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90}},
 {id:"SUP-SM8",kind:"suspension",title:"Attache Stil SM8 + cavalier Stil F 530",summary:"Suspension insérée à force sur une aile de poutrelle inférieure à 8 mm.",sourcePage:106,status:"Publié",data:{support_id:"SUP-METAL",reglage_min_exclu_mm:20,entraxe_suspentes_m:1.2,charge_suspente_kg:"65 ou 68 avec dB-F",poids_plafond_kg_m2:90}},
 {id:"RULE-ISO-LT6",kind:"rule",title:"Isolant inférieur à 6 kg/m²",summary:"Entraxe maximal des fourrures : 60 cm.",sourcePage:105,status:"Publié",data:{poids_min_kg_m2:0,poids_max_exclu_kg_m2:6,entraxe_fourrures_m:0.6,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-6-10",kind:"rule",title:"Isolant de 6 kg/m² à moins de 10 kg/m²",summary:"Entraxe maximal des fourrures : 50 cm.",sourcePage:105,status:"Publié",data:{poids_min_inclus_kg_m2:6,poids_max_exclu_kg_m2:10,entraxe_fourrures_m:0.5,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-10-15",kind:"rule",title:"Isolant de 10 à 15 kg/m²",summary:"Entraxe maximal des fourrures : 40 cm.",sourcePage:105,status:"Publié",data:{poids_min_inclus_kg_m2:10,poids_max_inclus_kg_m2:15,entraxe_fourrures_m:0.4,entraxe_suspentes_m:1.2}},
 {id:"RULE-ISO-GT15",kind:"rule",title:"Isolant supérieur à 15 kg/m²",summary:"Configuration bloquée : aucune règle n’est fournie dans les pages étudiées.",sourcePage:105,status:"À valider",data:{poids_min_exclu_kg_m2:15,action:"Bloquer la configuration"}},
 {id:"RULE-POSE",kind:"rule",title:"Pose des plaques",summary:"Plaques perpendiculaires ; entraxe réduit à 40 cm si pose parallèle ou plaque hydrofugée.",sourcePage:108,status:"Publié",data:{entraxe_reduit_m:0.4,vis_standard_cm:30,vis_feu_cm:15}},
 {id:"RULE-RIVE",kind:"rule",title:"Rail périphérique",summary:"Cornière Stil CR2 ou rail Stil F 530 fixé tous les 60 cm maximum.",sourcePage:107,status:"Publié",data:{entraxe_fixations_max_cm:60}},
 {id:"RULE-JOINTS",kind:"rule",title:"Joints de fractionnement",summary:"Aux joints du bâtiment, changements de support ou d’orientation, puis tous les 300 m² ou 25 m linéaires.",sourcePage:109,status:"Publié",data:{surface_max_m2:300,longueur_max_m:25}},
 {id:"RULE-LOAD",kind:"rule",title:"Charge ponctuelle d’accessoire",summary:"2 daN par surface de 1,20 × 1,20 m.",sourcePage:109,status:"Publié",data:{charge_dan:2,surface_reference:"1,20 × 1,20 m"}},
 {id:"SOURCE-INTEGRALE-2025",kind:"source",title:"L’Intégrale Placo® 2025",summary:"Source technique du système Placostil® sur fourrures Stil® F 530.",sourcePage:104,status:"Publié",data:{edition:"Juin 2025",pages:"104 à 109",document:"PLACO_INTEGRALE_01-2025_WEB_PaP.pdf"}},
 ...([0.4,0.5,0.6] as const).flatMap(spacing=>[1,2].map((layers):ReferenceRecord=>{const i=spacing===0.4?0:spacing===0.5?1:2;return {id:`QTY-${Math.round(spacing*100)}-${layers}L`,kind:"quantity",title:`Quantitatif ${layers===1?"simple":"double"} peau · entraxe ${Math.round(spacing*100)} cm`,summary:"Quantités indicatives pour 1 m², plafond de référence 8 × 10 m.",sourcePage:109,status:"Publié",data:{entraxe_fourrures_m:spacing,peaux:layers,plaque_m2:layers===1?1.05:2.10,fourrure_f530_ml:[2.52,2.10,1.79][i],rail_f530_ml:0.47,suspente_unite:[2.20,1.84,1.56][i],eclisse_unite:spacing===0.4?null:spacing===0.5?0.25:0.21,vis_premiere_peau_unite:layers===1?[20,17,15][i]:[13,11,10][i],vis_deuxieme_peau_unite:layers===2?[20,17,15][i]:null,bande_joint_ml:1.58,enduit_poudre_kg:0.37,enduit_pret_emploi_kg:0.53,entretoise_stil_flam_unite:spacing===0.6?1.68:null,base:"1 m² · plafond 8 × 10 m",note_enduit:"Poudre OU prêt à l’emploi",note_vis:"Longueur > épaisseur totale des plaques + 10 mm"}}}))
];

export const recordLabels:Record<RecordKind,string>={work:"Ouvrages",system:"Systèmes",product_family:"Familles",brand:"Marques",product:"Produits",product_model:"Modèles",commercial_reference:"Références commerciales",product_reference:"Anciennes références",board:"Plaques techniques",suspension:"Suspentes techniques",support:"Supports",rule:"Règles",quantity:"Quantitatifs",source:"Sources"};
