import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {f530Records} from "@/lib/f530-data";
const ADMIN="e.ganier@gmail.com";
async function auth(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();return {supabase,ok:user?.email?.toLowerCase()===ADMIN}}
export async function GET(){const {supabase,ok}=await auth();if(!ok)return NextResponse.json({error:"Non autorisé"},{status:401});const {data,error}=await supabase.from("reference_records").select("*").order("kind").order("title");if(error)return NextResponse.json({records:f530Records,storage:"local"});if(!data.length){const rows=f530Records.map(r=>({id:r.id,kind:r.kind,title:r.title,summary:r.summary,source_page:r.sourcePage,status:r.status,data:r.data}));const {error:seedError}=await supabase.from("reference_records").insert(rows);if(seedError)return NextResponse.json({records:f530Records,storage:"local"});return NextResponse.json({records:f530Records,storage:"supabase"})}return NextResponse.json({records:data.map(r=>({id:r.id,kind:r.kind,title:r.title,summary:r.summary,sourcePage:r.source_page,status:r.status,data:r.data})),storage:"supabase"})}
export async function POST(){const {supabase,ok}=await auth();if(!ok)return NextResponse.json({error:"Non autorisé"},{status:401});const rows=f530Records.map(r=>({id:r.id,kind:r.kind,title:r.title,summary:r.summary,source_page:r.sourcePage,status:r.status,data:r.data,updated_at:new Date().toISOString()}));const {error}=await supabase.from("reference_records").upsert(rows);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({count:rows.length})}
export async function PATCH(request:Request){const {supabase,ok}=await auth();if(!ok)return NextResponse.json({error:"Non autorisé"},{status:401});const r=await request.json();const {error}=await supabase.from("reference_records").update({title:r.title,summary:r.summary,status:r.status,data:r.data,updated_at:new Date().toISOString()}).eq("id",r.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
export async function PUT(request:Request){const {supabase,ok}=await auth();if(!ok)return NextResponse.json({error:"Non autorisé"},{status:401});const r=await request.json();const {error}=await supabase.from("reference_records").insert({id:r.id,kind:r.kind,title:r.title,summary:r.summary,source_page:r.sourcePage,status:r.status,data:r.data});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({record:r})}
export async function DELETE(request:Request){const {supabase,ok}=await auth();if(!ok)return NextResponse.json({error:"Non autorisé"},{status:401});const {id}=await request.json();if(typeof id!=="string"||!id.startsWith("REF-"))return NextResponse.json({error:"Référence invalide"},{status:400});const {error}=await supabase.from("reference_records").delete().eq("id",id).eq("kind","commercial_reference");if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
