"use client";
import {useEffect,useMemo,useState} from "react";
import {f530Records,recordLabels,type ReferenceRecord} from "@/lib/f530-data";
type AppSection="overview"|"works"|"systems"|"supplies"|"rules"|"sources";
const sectionLabels:Record<AppSection,string>={overview:"Vue d’ensemble",works:"Ouvrages",systems:"Systèmes",supplies:"Fournitures",rules:"Règles et quantitatifs",sources:"Sources"};

export default function AdminApp(){
 const [records,setRecords]=useState<ReferenceRecord[]>(f530Records),[section,setSection]=useState<AppSection>("overview"),[selected,setSelected]=useState<ReferenceRecord|null>(null),[query,setQuery]=useState(""),[storage,setStorage]=useState("loading");
 useEffect(()=>{fetch("/api/records").then(r=>r.json()).then(x=>{if(x.records?.length)setRecords(x.records);setStorage(x.storage||"local")}).catch(()=>setStorage("local"))},[]);
 const sectionKinds=useMemo(()=>section==="works"?["work"]:section==="systems"?["system","support","suspension"]:section==="rules"?["rule","quantity"]:section==="sources"?["source"]:[],[section]);
 const shown=useMemo(()=>records.filter(r=>sectionKinds.includes(r.kind)&&`${r.title} ${r.summary} ${r.id}`.toLowerCase().includes(query.toLowerCase())),[records,sectionKinds,query]);
 const counts=Object.fromEntries(["work","system","product_family","brand","product_reference","support","suspension","rule","quantity","source"].map(k=>[k,records.filter(r=>r.kind===k).length]));
 const open=(k:AppSection)=>{setSection(k);setSelected(null)};
 const save=async(next:ReferenceRecord)=>{const response=await fetch("/api/records",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!response.ok)throw new Error();setRecords(rs=>rs.map(r=>r.id===next.id?next:r));setSelected(next)};
 const seed=async()=>{const response=await fetch("/api/records",{method:"POST"});if(!response.ok)throw new Error();setStorage("supabase")};
 return <div className="shell"><aside className="side"><div className="brand"><b>P</b><div><strong>Plaquisto</strong><small>Administration</small></div></div><nav><label>Catalogue métier</label>{(["overview","works","systems","supplies","rules","sources"] as AppSection[]).map(k=><button key={k} className={section===k?"on":""} onClick={()=>open(k)}>{sectionLabels[k]} {k!=="overview"&&<i>{k==="works"?counts.work:k==="systems"?counts.system:k==="supplies"?counts.product_reference:k==="rules"?counts.rule+counts.quantity:counts.source}</i>}</button>)}</nav><div className="release"><small>BASE ACTIVE</small><strong>Catalogue Plaquisto · V0</strong><span>● {storage==="supabase"?"Supabase synchronisé":storage==="loading"?"Connexion…":"Mode local"}</span></div><div className="user"><b>EG</b><div><strong>Administrateur</strong><small>e.ganier@gmail.com</small></div><form action="/auth/signout" method="post"><button title="Se déconnecter">↪</button></form></div></aside><main><header><span>Plaquisto / <strong>{sectionLabels[section]}</strong></span><span className="source-chip">Catalogue technique et commercial</span></header>{selected?<Editor record={selected} onBack={()=>setSelected(null)} onSave={save}/>:section==="overview"?<Overview records={records} counts={counts} storage={storage} onSeed={seed} onOpen={open}/>:section==="supplies"?<Supplies records={records} onSelect={setSelected}/>:<List title={sectionLabels[section]} records={shown} query={query} setQuery={setQuery} onSelect={setSelected}/>}</main></div>
}

function Overview({records,counts,storage,onSeed,onOpen}:{records:ReferenceRecord[];counts:Record<string,number>;storage:string;onSeed:()=>Promise<void>;onOpen:(k:AppSection)=>void}){const [message,setMessage]=useState("");const quantities=records.filter(r=>r.kind==="quantity");return <><section className="hero"><div><span className="badge green">Catalogue structuré</span><h1>De l’ouvrage<br/>à la référence achetée.</h1><p>Les systèmes et règles définissent le besoin technique. Les familles, marques et références permettent ensuite de choisir et chiffrer les fournitures.</p></div><aside><small>ÉTAT DU CATALOGUE</small><strong>{counts.product_reference} références produit</strong><span>{counts.product_family} familles · {counts.brand} marque</span><i><b style={{width:"100%"}}/></i><em>{records.filter(r=>r.status==="À valider").length} point à compléter</em></aside></section><section className="stats"><Stat icon="O" title="OUVRAGES" value={String(counts.work)} note="Plafonds aujourd’hui"/><Stat icon="S" title="SYSTÈMES" value={String(counts.system)} note="Placostil F 530"/><Stat icon="F" title="FOURNITURES" value={String(counts.product_reference)} note="Famille, marque, référence"/><Stat icon="R" title="RÈGLES" value={String(counts.rule+counts.quantity)} note="Contrôles et quantités"/></section><section className="grids"><article className="panel"><div className="panel-title"><div><small>CALCUL IOS</small><h2>Quantités par m²</h2></div><span className="badge blue">Base 8 × 10 m</span></div><div className="matrix quantity-head"><span>Entraxe</span><span>Peaux</span><span>Plaques</span><span>Fourrures</span></div>{quantities.map(r=><button className="matrix quantity-row" key={r.id} onClick={()=>onOpen("rules")}><strong>{Number(r.data.entraxe_fourrures_m)*100} cm</strong><span>{r.data.peaux}</span><span>{r.data.plaque_m2} m²</span><span>{r.data.fourrure_f530_ml} ml</span></button>)}</article><article className="panel"><div className="panel-title"><div><small>SYNCHRONISATION</small><h2>Base de données</h2></div><span className={`badge ${storage==="supabase"?"green":"gold"}`}>{storage==="supabase"?"Connectée":"À initialiser"}</span></div><p className="plain-copy">Le catalogue alimente Plaquisto Admin et le configurateur iOS avec une source commune.</p>{storage!=="supabase"&&<button className="primary" onClick={()=>onSeed().then(()=>setMessage("Base Supabase initialisée.")).catch(()=>setMessage("La table Supabase doit d’abord être créée."))}>Initialiser dans Supabase</button>}<p className="save-message">{message}</p><div className="notice"><b>i</b><span><strong>Prix à compléter</strong><small>Chaque référence pourra recevoir son conditionnement, son unité de vente et ton prix hors taxes.</small></span></div></article></section></>}
function Stat({icon,title,value,note}:{icon:string;title:string;value:string;note:string}){return <article><b>{icon}</b><div><small>{title}</small><strong>{value}</strong><p>{note}</p></div></article>}
function Supplies({records,onSelect}:{records:ReferenceRecord[];onSelect:(r:ReferenceRecord)=>void}){
 const families=records.filter(r=>r.kind==="product_family"),brands=records.filter(r=>r.kind==="brand"),references=records.filter(r=>r.kind==="product_reference");
 const [familyId,setFamilyId]=useState(families[0]?.id||""),[brandId,setBrandId]=useState("BRAND-PLACO");
 const visible=references.filter(r=>r.data.family_id===familyId&&r.data.brand_id===brandId);
 return <section className="page"><div className="title"><div><small>CATALOGUE FOURNITURES</small><h1>Familles, marques et références</h1><p>Organisez les produits techniques puis renseignez leurs dimensions, conditionnements et prix.</p></div><span className="badge green">{references.length} références</span></div><div className="catalog-grid"><article className="catalog-column"><header><small>1 · FAMILLES</small><strong>{families.length}</strong></header>{families.map(f=><button key={f.id} className={familyId===f.id?"selected":""} onClick={()=>setFamilyId(f.id)}><span><b>{f.title}</b><small>{references.filter(r=>r.data.family_id===f.id).length} référence(s)</small></span><i>›</i></button>)}</article><article className="catalog-column"><header><small>2 · MARQUES</small><strong>{brands.length}</strong></header>{brands.map(b=><button key={b.id} className={brandId===b.id?"selected":""} onClick={()=>setBrandId(b.id)}><span><b>{b.title}</b><small>{references.filter(r=>r.data.brand_id===b.id&&r.data.family_id===familyId).length} référence(s) dans cette famille</small></span><i>›</i></button>)}</article><article className="catalog-column references"><header><small>3 · RÉFÉRENCES</small><strong>{visible.length}</strong></header>{visible.length===0?<p className="catalog-empty">Aucune référence pour cette sélection.</p>:visible.map(r=><button key={r.id} onClick={()=>onSelect(r)}><span><b>{r.title}</b><small>{r.data.reference_fabricant?`Réf. ${r.data.reference_fabricant}`:"Référence fabricant à renseigner"}</small></span><em>{r.data.prix_ht?`${r.data.prix_ht} € HT`:"Prix à saisir"}</em></button>)}</article></div></section>
}
function List({title,records,query,setQuery,onSelect}:{title:string;records:ReferenceRecord[];query:string;setQuery:(s:string)=>void;onSelect:(r:ReferenceRecord)=>void}){return <section className="page"><div className="title"><div><small>PLAFONDS STIL® F 530</small><h1>{title}</h1><p>Données techniques structurées et modifiables.</p></div><span className="badge green">{records.length} fiches</span></div><div className="tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une donnée…"/><span>Cliquez sur une ligne pour la modifier</span></div><div className="table"><table><thead><tr><th>Donnée</th><th>Valeurs principales</th><th>Source</th><th>Statut</th><th/></tr></thead><tbody>{records.map(r=><tr key={r.id} onClick={()=>onSelect(r)}><td><strong>{r.title}</strong><small>{r.id}</small></td><td><span className="row-summary">{r.summary}</span></td><td>Page {r.sourcePage}</td><td><span className={`badge ${r.status==="Publié"?"green":"gold"}`}>{r.status}</span></td><td>›</td></tr>)}</tbody></table></div></section>}
function Editor({record,onBack,onSave}:{record:ReferenceRecord;onBack:()=>void;onSave:(r:ReferenceRecord)=>Promise<void>}){const [draft,setDraft]=useState(record),[json,setJson]=useState(JSON.stringify(record.data,null,2)),[message,setMessage]=useState("");const submit=async()=>{try{await onSave({...draft,data:JSON.parse(json)});setMessage("Modifications enregistrées dans Supabase.")}catch{setMessage("Enregistrement impossible. Vérifiez les valeurs.")}};return <section className="page detail"><button className="back" onClick={onBack}>← Retour à la liste</button><div className="detail-title"><div><p><span className="badge blue">{recordLabels[record.kind]}</span> <span className={`badge ${draft.status==="Publié"?"green":"gold"}`}>{draft.status}</span></p><h1>{record.title}</h1><code>{record.id}</code></div><button className="primary" onClick={submit}>Enregistrer</button></div><div className="edit-grid"><article className="box form-box"><h2>Informations utilisées par l’app</h2><label>Titre<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Résumé<textarea value={draft.summary} onChange={e=>setDraft({...draft,summary:e.target.value})}/></label><label>Statut<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as ReferenceRecord["status"]})}><option>Publié</option><option>À valider</option></select></label><label>Valeurs techniques<textarea className="json" value={json} onChange={e=>setJson(e.target.value)} spellCheck={false}/></label><p className="save-message">{message}</p></article><aside><article className="box provenance"><h2>Traçabilité</h2><small>DOCUMENT</small><strong>L’Intégrale Placo® 2025</strong><small>PAGE SOURCE</small><strong>Page {record.sourcePage}</strong><small>UTILISATION</small><strong>Administration + future app iOS</strong></article><article className="notice"><b>!</b><span><strong>Modification sensible</strong><small>Cette valeur influencera les contrôles et les calculs de l’app iOS.</small></span></article></aside></div></section>}
