"use client";

import { useMemo, useState } from "react";

type System = "F530" | "Autoportant";
type Config = { id:string; system:System; name:string; note:string; support:string; facing:string; layers:number; spacing:number; span?:number; performance?:string; source:string; status:"Vérifié"|"Anomalie source"; active:boolean; details:string[] };

const configs: Config[] = [
  {id:"CFG_F530_WOOD_BA13_1L_050",system:"F530",name:"Bois · BA13 simple",note:"Suspente courte / longue / maxi",support:"Bois horizontal",facing:"BA13 standard",layers:1,spacing:500,performance:"REI15",source:"SP00022956",status:"Vérifié",active:true,details:["Isolant 100 mm · 6 à 10 kg/m²","Profil QP_F530_050_SINGLE_13","2 vis TTPC35 par suspente"]},
  {id:"CFG_F530_WOOD_BA13_2L_040",system:"F530",name:"Bois · BA13 double",note:"Configuration forte charge",support:"Bois horizontal",facing:"BA13 standard",layers:2,spacing:400,performance:"REI30",source:"SP00022976",status:"Vérifié",active:true,details:["Isolant 100 mm · 10 à 15 kg/m²","Profil QP_F530_040_DOUBLE_13","Parement total 2,10 m²/m²"]},
  {id:"CFG_F530_WOOD_PHONIC13_2L_060",system:"F530",name:"Bois · Phonique double",note:"Solution acoustique",support:"Bois horizontal",facing:"Placo Phonique BA13",layers:2,spacing:600,performance:"57 dB · REI30",source:"SP00022968",status:"Vérifié",active:true,details:["Isolant 100 mm","Performance de la solution complète","Profil QP_F530_060_DOUBLE_13"]},
  {id:"CFG_F530_WOOD_BA18S_2L_050",system:"F530",name:"Bois · BA18S double",note:"Protection incendie",support:"Bois horizontal",facing:"BA18S",layers:2,spacing:500,performance:"REI60",source:"SP00022984",status:"Vérifié",active:true,details:["Isolant 100 mm · 6 à 10 kg/m²","Vis TTPC35 puis TTPC45","Profil exact fabricant"]},
  {id:"CFG_F530_CONCRETE_BA13_1L_060_ROD",system:"F530",name:"Béton · BA13 simple",note:"Tige filetée + cavalier",support:"Dalle béton",facing:"BA13 standard",layers:1,spacing:600,source:"SY2_44870480",status:"Vérifié",active:true,details:["Sans isolant","Tige filetée Ø6","Longueur calculée selon le plénum"]},
  {id:"CFG_F530_CONCRETE_BA13_1L_060_DBF",system:"F530",name:"Béton · BA13 acoustique",note:"Cavalier dB-F",support:"Dalle béton",facing:"BA13 standard",layers:1,spacing:600,performance:"66 dB",source:"SP00035378",status:"Vérifié",active:true,details:["Plénum minimum 130 mm","Isolant 80 mm","Performance de la solution complète"]},
  {id:"CFG_AUTO_M48_SINGLE_BA13_060_SP00021949",system:"Autoportant",name:"M48 simple · BA13",note:"Entretoise à mi-portée",support:"Béton / hourdis",facing:"BA13 standard",layers:1,spacing:600,span:1.85,source:"SP00021949",status:"Anomalie source",active:true,details:["Rail R48","Isolant 100 mm · moins de 6 kg/m²","Suspente MD conservée mais non calculée"]},
  {id:"CFG_AUTO_M48_DOUBLE_PHONIC13_060_SP00015376",system:"Autoportant",name:"M48 double · Phonique",note:"Montants dos à dos",support:"Non précisé",facing:"Placo Phonique BA13",layers:1,spacing:600,span:2.1,source:"SP00015376",status:"Vérifié",active:true,details:["Rail R48","TRPF13 tous les 400 mm","Vis visibles tous les 150 mm"]},
  {id:"CFG_AUTO_M48_DOUBLE_BA25_2L_050_SP00022033",system:"Autoportant",name:"M48 double · 2 × BA25",note:"Protection incendie renforcée",support:"Béton / hourdis",facing:"BA25",layers:2,spacing:500,span:1.9,performance:"REI120",source:"SP00022033",status:"Vérifié",active:false,details:["Rail R48","PV RS_21_008","Masquée en attendant l’interface feu"]},
  {id:"CFG_AUTO_M70_SINGLE_BA13_060_SP00003068",system:"Autoportant",name:"M70 simple · BA13",note:"Entretoise à mi-portée",support:"Béton / hourdis",facing:"BA13 standard",layers:1,spacing:600,span:2.55,source:"SP00003068",status:"Vérifié",active:true,details:["Rail R70","Isolant 100 mm · moins de 6 kg/m²","Configuration fabricant exacte"]},
  {id:"CFG_AUTO_M70_DOUBLE_BA13_060_SP00015410",system:"Autoportant",name:"M70 double · BA13",note:"Montants dos à dos",support:"Béton / hourdis",facing:"BA13 standard",layers:1,spacing:600,span:3,performance:"REI30",source:"SP00015410",status:"Vérifié",active:true,details:["Rail R70","TRPF13 tous les 400 mm","Performance feu estimée Placo"]},
  {id:"CFG_AUTO_M90_SINGLE_BA13_060_SP00022201",system:"Autoportant",name:"M90 simple · BA13",note:"Entretoise à mi-portée",support:"Charpente métallique",facing:"BA13 standard",layers:1,spacing:600,span:3.1,performance:"R15",source:"SP00022201",status:"Vérifié",active:true,details:["Rail R90","Isolant 100 mm · moins de 6 kg/m²","Configuration fabricant exacte"]},
  {id:"CFG_AUTO_M90_DOUBLE_BA13_060_SP00022204",system:"Autoportant",name:"M90 double · BA13",note:"Montants dos à dos",support:"Charpente métallique",facing:"BA13 standard",layers:1,spacing:600,span:3.8,performance:"R15",source:"SP00022204",status:"Vérifié",active:true,details:["Rail R90","TRPF13 tous les 400 mm","Configuration fabricant exacte"]},
  {id:"CFG_AUTO_M100_SINGLE_BA13_060_SP00021660",system:"Autoportant",name:"M100 simple · BA13",note:"Entretoise à mi-portée",support:"Béton / hourdis",facing:"BA13 standard",layers:1,spacing:600,span:3.2,source:"SP00021660",status:"Vérifié",active:true,details:["Rail R100","2 fixations superposées tous les 600 mm","Liaison rail/montant TRPF25"]},
  {id:"CFG_AUTO_M100_DOUBLE_BA13_060_SP00021663",system:"Autoportant",name:"M100 double · BA13",note:"Portée exacte 3,95 m",support:"Béton / hourdis",facing:"BA13 standard",layers:1,spacing:600,span:3.95,source:"SP00021663",status:"Anomalie source",active:true,details:["Rail R100","2 TRPF13 superposées tous les 400 mm","Suspente MD conservée mais non calculée"]},
  {id:"CFG_AUTO_M100_DOUBLE_PHONIC13_060_SP00021642",system:"Autoportant",name:"M100 double · Phonique",note:"Portée exacte 3,85 m",support:"Béton / hourdis",facing:"Placo Phonique BA13",layers:1,spacing:600,span:3.85,source:"SP00021642",status:"Vérifié",active:true,details:["Rail R100","2 TRPF13 superposées tous les 400 mm","2 fixations de rail par station"]},
];

const matrix = [["M48","2,10 m","2,50 m"],["M70","2,70 m","3,20 m"],["M90","3,15 m","3,70 m"],["M100","3,30 m","3,90 m"]];
const tests = ["F530 bois BA13 · entraxe 500","F530 double BA13 · entraxe 400","F530 BA18S · REI60","F530 béton · tige filetée","Autoportant M48 · limite exacte","Autoportant M70 double","Autoportant M100 double · 3,95 m","Règle exacte prioritaire","Suspente MD non ajoutée"];

function Badge({children,tone="plain"}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

export default function Home(){
  const [section,setSection]=useState<"Accueil"|System|"Sources"|"Tests">("Accueil");
  const [query,setQuery]=useState("");
  const [filter,setFilter]=useState("Tous");
  const [selected,setSelected]=useState<Config|null>(null);
  const rows=useMemo(()=>configs.filter(c=>(section==="Accueil"||section==="Sources"||section==="Tests"||c.system===section)&&(`${c.name} ${c.id} ${c.facing} ${c.source}`.toLowerCase().includes(query.toLowerCase()))&&(filter==="Tous"||c.status===filter)),[section,query,filter]);
  const go=(next:typeof section)=>{setSection(next);setSelected(null)};
  return <div className="shell">
    <aside className="side"><div className="brand"><b>P</b><div><strong>Plaquisto</strong><small>Administration</small></div></div><nav><label>Vue générale</label><button className={section==="Accueil"?"on":""} onClick={()=>go("Accueil")}>Tableau de bord</button><label>Référentiel métier</label><button className={section==="F530"?"on":""} onClick={()=>go("F530")}>Plafonds F530 <i>6</i></button><button className={section==="Autoportant"?"on":""} onClick={()=>go("Autoportant")}>Autoportants <i>10</i></button><button className={section==="Sources"?"on":""} onClick={()=>go("Sources")}>Sources <i>23</i></button><button className={section==="Tests"?"on":""} onClick={()=>go("Tests")}>Tests métier <i>18</i></button></nav><div className="release"><small>VERSION PUBLIÉE</small><strong>Plafonds V1.0</strong><span>● Référentiel actif</span></div><div className="user"><b>EG</b><div><strong>Administrateur</strong><small>Compte principal</small></div></div></aside>
    <main><header><span>Référentiel métier　/　<strong>{section}</strong></span><button>Préparer une publication</button></header>
    {section==="Accueil"&&!selected&&<Dashboard onOpen={(c)=>setSelected(c)}/>} 
    {(section==="F530"||section==="Autoportant")&&!selected&&<section className="page"><div className="title"><div><small>PLAFONDS</small><h1>{section==="F530"?"Configurations F530":"Plafonds autoportants"}</h1><p>{section==="F530"?"Plafonds suspendus classés par support et parement.":"Configurations exactes M48, M70, M90 et M100."}</p></div><button>+ Nouvelle configuration</button></div><div className="tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher par nom, code, plaque ou source…"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Tous</option><option>Vérifié</option><option>Anomalie source</option></select><span>{rows.length} résultats</span></div><div className="table"><table><thead><tr><th>Configuration</th><th>Parement</th><th>Entraxe</th><th>{section==="F530"?"Support":"Portée max."}</th><th>Performance</th><th>Source</th><th>Statut</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>setSelected(c)}><td><strong>{c.name}</strong><small>{c.id}</small></td><td>{c.facing}<small>{c.layers} peau{c.layers>1?"x":""}</small></td><td>{c.spacing} mm</td><td>{section==="F530"?c.support:`${c.span?.toFixed(2).replace(".",",")} m`}</td><td>{c.performance?<Badge tone="blue">{c.performance}</Badge>:"—"}</td><td><code>{c.source}</code></td><td><Badge tone={c.status==="Vérifié"?"green":"red"}>{c.status}</Badge></td><td>›</td></tr>)}</tbody></table></div></section>}
    {section==="Sources"&&!selected&&<Sources/>}{section==="Tests"&&!selected&&<Tests/>}{selected&&<Detail config={selected} back={()=>setSelected(null)}/>}</main>
  </div>
}

function Dashboard({onOpen}:{onOpen:(c:Config)=>void}){return <><section className="hero"><div><Badge tone="green">V0 opérationnelle</Badge><h1>Le référentiel Plafonds,<br/>clair et vérifiable.</h1><p>Consultez les configurations, contrôlez leurs sources et préparez les règles qui alimenteront les calculs Plaquisto.</p></div><aside><small>ÉTAT DU RÉFÉRENTIEL</small><strong>16 configurations visibles</strong><span>Dernière vérification : aujourd’hui</span><i><b/></i><em>18 tests métier prêts</em></aside></section><section className="stats"><Stat icon="F" title="CONFIGURATIONS F530" value="6" note="3 supports représentés"/><Stat icon="A" title="AUTOPORTANTS" value="10" note="M48 à M100"/><Stat icon="✓" title="DONNÉES VÉRIFIÉES" value="14" note="Sources officielles"/><Stat icon="!" title="POINTS À CONTRÔLER" value="2" note="Anomalies conservées"/></section><section className="grids"><article className="panel"><div className="panel-title"><div><small>AUTOPORTANT</small><h2>Portées génériques Placo</h2></div><Badge>Entraxe 600 mm</Badge></div><div className="matrix head"><span>Montant</span><span>Simple</span><span>Double</span></div>{matrix.map(r=><div className="matrix" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}<p className="info">Les configurations exactes restent prioritaires sur ce tableau générique.</p></article><article className="panel"><div className="panel-title"><div><small>À TRAITER</small><h2>Points de vigilance</h2></div><Badge tone="red">2 alertes</Badge></div><button className="alert" onClick={()=>onOpen(configs[6])}><b>!</b><span><strong>Suspente MD dans une nomenclature</strong><small>Conservée pour traçabilité, désactivée dans le calcul.</small></span>›</button><button className="alert"><b>?</b><span><strong>Ratios d’éclisses à compléter</strong><small>Certains profils à entraxe 400 mm restent à vérifier.</small></span>›</button></article></section></>}
function Stat({icon,title,value,note}:{icon:string;title:string;value:string;note:string}){return <article><b>{icon}</b><div><small>{title}</small><strong>{value}</strong><p>{note}</p></div></article>}
function Sources(){return <section className="page"><div className="title"><div><small>TRAÇABILITÉ</small><h1>Sources du référentiel</h1><p>Chaque donnée technique conserve l’origine qui justifie son utilisation.</p></div></div><div className="cards"><article><Badge tone="blue">Guide officiel</Badge><h2>Le Compagnon Placo</h2><p>Mise en œuvre, guide de choix plafonds, F530 et autoportants.</p><strong>11 règles liées</strong></article><article><Badge tone="green">Pages fabricant</Badge><h2>Solutions exactes Placo</h2><p>Pages PIM utilisées pour les portées, quantités et performances.</p><strong>21 configurations liées</strong></article><article><Badge tone="gold">Règle Plaquisto</Badge><h2>Overlay métier Plaquisto</h2><p>Éclisses, périphérie, tiges filetées et règles de chantier.</p><strong>7 règles liées</strong></article></div></section>}
function Tests(){return <section className="page"><div className="title"><div><small>VALIDATION</small><h1>Tests métier</h1><p>Contrôles automatiques prévus avant chaque publication.</p></div><Badge tone="green">18 / 18 prêts</Badge></div><div className="test-list">{tests.map((t,i)=><article key={t}><b>✓</b><div><strong>{t}</strong><small>TEST-{String(i+1).padStart(3,"0")}</small></div><Badge tone="green">Prêt</Badge></article>)}</div></section>}
function Detail({config,back}:{config:Config;back:()=>void}){const [active,setActive]=useState(config.active);const [visible,setVisible]=useState(config.active);return <section className="page detail"><button className="back" onClick={back}>← Retour aux configurations</button><div className="detail-title"><div><p><Badge tone={config.system==="F530"?"blue":"gold"}>{config.system}</Badge> <Badge tone={config.status==="Vérifié"?"green":"red"}>{config.status}</Badge></p><h1>{config.name}</h1><code>{config.id}</code></div><aside><button>Dupliquer</button><button>Modifier</button></aside></div><div className="detail-grid"><div><article className="box"><h2>Caractéristiques techniques</h2><div className="facts"><Fact a="Support" b={config.support}/><Fact a="Parement" b={config.facing}/><Fact a="Nombre de peaux" b={String(config.layers)}/><Fact a="Entraxe" b={`${config.spacing} mm`}/>{config.span&&<Fact a="Portée maximale" b={`${config.span.toFixed(2).replace(".",",")} m`}/>}<Fact a="Performance" b={config.performance||"Non renseignée"}/></div></article><article className="box"><h2>Règles et quantitatifs</h2><ul>{config.details.map(x=><li key={x}>✓　{x}</li>)}</ul></article>{config.status==="Anomalie source"&&<article className="warning"><b>!</b><div><strong>Anomalie conservée</strong><p>La nomenclature source contient une Suspente MD. Elle reste visible pour la traçabilité mais n’est pas ajoutée au calcul standard.</p></div></article>}</div><aside><article className="box"><h2>Publication</h2><label><span><strong>Active pour le calcul</strong><small>Utilisable dans Plaquisto</small></span><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/></label><label><span><strong>Visible dans l’app</strong><small>Proposée aux utilisateurs</small></span><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/></label><p className="demo">Modifications locales de démonstration</p></article><article className="box provenance"><h2>Provenance</h2><small>SOURCE PRINCIPALE</small><code>{config.source}</code><p>Page solution officielle Placo</p><hr/><small>PRIORITÉ</small><strong>100 · Configuration exacte</strong><small>VALIDATION</small><strong>{config.status}</strong></article></aside></div></section>}
function Fact({a,b}:{a:string;b:string}){return <div><small>{a}</small><strong>{b}</strong></div>}
